#fortuneList="computers asoiaf food iasip humorists linux love matrix parks-and-recreation pets riddles sports starwars wisdom zippy"
fortuneList="food wisdom zippy pets"
fortune $(echo $fortuneList) | cowsay -f $(cowsay -l | shuf -n1) | lolcat -p 9 -F 0.1

# Command history
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
setopt appendhistory

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Use powerline
USE_POWERLINE="true"
# Has weird character width
# Example:
#    is not a diamond
HAS_WIDECHARS="false"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

# powerlevel10k source
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# colorls config
alias ls="colorls --sd"
alias ll="colorls -lA --sd"
alias lc="colorls -lA --sd"
source $(dirname $(gem which colorls))/tab_complete.sh
path+=(
  $(ruby -e 'puts File.join(Gem.user_dir, "bin")')
)

# other aliases
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias du='du -h --max-depth=1 .'         # estimate file space usage without descending into folders
alias free='free --si -h'                 # more friendly free memory
alias more=less
alias vi=nvim
alias vim=nvim

# keybinds
# CTRL+left/right
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
# home/end
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
# delete
bindkey "^[[3~" vi-delete-char

# ssh completion
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ -r ~/.ssh/known_hosts ]]; then
  h=($h ${${${(f)"$(cat ~/.ssh/known_hosts{,2} || true)"}%%\ *}%%,*}) 2>/dev/null
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi

#command completion
autoload -Uz compinit

compinit

